### ISSUE TITLE
Creating login links for non users

### ISSUE THREAD

**Issue by sauliuslt** [DarkGhostHunter/Passless#7]
Hi,

I have a scenario where i have a list of emails and i want to generate login link for each email and send this link be email. Once person click the link I want new user to be created in Laravel and signed in (skip registration step).
is where a way to call passless function like passless::createLoginLink('email@address.com') ???

**Comment by DarkGhostHunter** [comment]
If you check the [LoginNotification](https://github.com/DarkGhostHunter/Passless/blob/master/src/LoginNotification), you will see the method [that returns the login link to be used inside the mail](https://github.com/DarkGhostHunter/Passless/blob/master/src/LoginNotification.php#L121).

You can adapt that code into whatever you want, wherever you want in your application.

> Once person click the link I want new user to be created in Laravel and signed in (skip registration step).

For that to work, you will need to create/persist the User model using the Authenticatable contract, and once done pass them to a loop which will send the emails. An alternative is to create the Authenticatable User when they hit your "ActivationController", which will afterwards log in him and redirect them to the dashboard or homepage, which is what you want.

This is because when they try to log in using the login link, it will use any User Provider you set, and in consequence, a User implementing the Authenticatable contract, so the rest of the Authentication mechanism can work.

Finally, since this is not an issue, I will close it. Happy coding.
